blank_issues_enabled: false
contact_links:
  - name: "⛔ Question"
    url: https://t.me/PhotoboothGroup
    about: "Please do not use GitHub for asking questions. Instead, please visit our Community at Telegram. Thanks in advance for helping us keep the issue tracker clean!"