name: Build

on:
  push:
    branches:
      - dev
      - stable2
      - stable3
  pull_request:
    branches:
      - dev
      - stable2
      - stable3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install modules
        run: yarn install
      - name: Build
        run: yarn build
      - name: Get git status
        run: git status
      - name: Pack zip
        run: yarn pack:build
      - name: Publish zip
        uses: actions/upload-artifact@v2
        with:
          name: photobooth
          path: archives/photobooth-*.zip

