name: gulp-sass

on:
  push:
    branches:
      - dev
      - stable3
    paths:
      - '**.scss'
  pull_request:
    branches:
      - dev
      - stable3
    paths:
      - '**.scss'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install modules
      run: yarn install
    - name: Running gulp-sass
      run: yarn build:sass
