name: Lint

on:
  push:
    branches:
      - dev
      - stable3
    paths:
      - '**.js'
  pull_request:
    branches:
      - dev
      - stable3
    paths:
      - '**.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install modules
      run: yarn install
    - name: Lint
      run: yarn eslint
